name: run.yml
on:
  workflow_dispatch:
  # Run every Sunday night
  schedule:
  - cron: '55 23 * * 6'

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Run script
      run: Rscript /app/R/main.R
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Interactive debug
      if: ${{ always() && runner.debug == '1' && github.run_attempt != '1' }}
      uses: r-hub/actions/ssh-server@main
