
name: run.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '46 * * * *'

permissions: read-all

jobs:
  cran-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Update
      run: Rscript index.R
      working-directory: /app
      env:
        R_APP_WORKSPACE: ${{ github.workspace }}
        R_APP_TEMP: ${{ runner.temp }}
    - name: Deploy to GitHub pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        clean: false
        branch: gh-pages
        folder: .
